[project]
name = "lps-insight-lab"
version = "0.1.0"
description = "LPS Insight Lab"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "jupyterlab>=4.4.6",
  "matplotlib>=3.10.5",
  "numpy>=2.3.2",
  "pandas>=2.3.2",
  "seaborn>=0.13.2",
]
